#！encoding: utf-8
"""Subclass of If_Condition_Panel, which is generated by wxFormBuilder."""

import wx
import GUI_IF_Codition
import logging
from LuaProgrammingGUI.test.control.control_parameters.control_if_condition import IFConditionControl
# Implementing If_Condition_Panel
class Panel_edit_ifcondition( GUI_IF_Codition.If_Condition_Panel ):

        def __init__(self, parent):

            self.ifcontrol = IFConditionControl(self)
            self.log = logging
            GUI_IF_Codition.If_Condition_Panel.__init__( self, parent )
            self.parent = parent

        # Handlers for If_Condition_Panel events.
        def set_choose_mode( self, event ):
            # TODO: Implement set_choose_mode
            self.ifcontrol.set_choose_mode(event.EventObject)

        def add_condition( self, event ):
            # TODO: Implement add_condition
            self.ifcontrol.add_condition(event.EventObject)

        def delete_condition( self, event ):
            # TODO: Implement delete_condition
            self.ifcontrol.delete_conditon(event.EventObject)

        def choose_condition( self, event ):
            # TODO: Implement choose_condition
            self.ifcontrol.choose_condition(event.EventObject)

        def choose_operation( self, event ):
            # TODO: Implement choose_operation
            self.ifcontrol.choose_operation(event.EventObject)

        def choose_value( self, event ):
            # TODO: Implement choose_value
            self.ifcontrol.choose_value(event.EventObject)
	
	
if __name__ == '__main__':
    app = wx.App()
    Panel_edit_ifcondition(None).Show(True)
    app.MainLoop()