"""Subclass of panel_control_parameters, which is generated by wxFormBuilder."""

import GUI_control_parameters
from LuaProgrammingGUI.test.control.control_parameters import control_parameters
from LuaProgrammingGUI.test.control.tools import view_tools
try:
    from wx.lib.pubsub import pub
except ImportError:
    from pubsub import pub

# Implementing panel_control_parameters
class panel_control_paras( GUI_control_parameters.panel_control_parameters ):
	def __init__( self, parent, id, pos, size, style ):

		self.control = control_parameters.Control(self)
		# self.controlshow = control_process_showdata.ShowDataControl(self)
		GUI_control_parameters.panel_control_parameters.__init__(self, parent)
		view_tools.config_control(self, id, pos, size, style)


	# def _unselete_process_all( self, event ):
	# 	self.control.unselete_process_all()