"""Subclass of Frame_controlprocess, which is generated by wxFormBuilder."""

import wx
import GUI_controlprocess

# Implementing Frame_controlprocess
class Frame_controlprocess( GUI_controlprocess.Frame_controlprocess ):
	def __init__( self, parent ):
		GUI_controlprocess.Frame_controlprocess.__init__( self, parent )
	
