"""Subclass of Panel_ChooseFunc, which is generated by wxFormBuilder."""

import GUI_functionlist
from LuaProgrammingGUI.test.control.control_function_list import control_function
from LuaProgrammingGUI.test.control.tools import view_tools


# Implementing Panel_ChooseFunc
class Panel_ChooseFunc( GUI_functionlist.Panel_ChooseFunc ):
	def __init__( self, parent, id, pos, size, style ):
		GUI_functionlist.Panel_ChooseFunc.__init__( self, parent )
		self.func_path = None
		self.current_data = None
		self.control = control_function.Control(self, self.func_path)
		view_tools.config_control(self, id, pos, size, style)
		self.config()

	# Handlers for Panel_ChooseFunc events.
	def update_func( self, event ):
		# TODO: Implement update_func
		self.control.Refresh(event.EventObject)
		print self.control.get_selection()
		print self.control.get_selectionstr()
		print self.control.get_selectionparas()
	
	def config(self):
		self.m_listBox_choosefunction.SetItems(self.control.get_items_keys())
		if len(self.m_listBox_choosefunction.GetItems()) > 0:
			self.m_listBox_choosefunction.SetSelection(0)
			self.control.Refresh(self.m_listBox_choosefunction)
		print self.control.get_selection()
		print self.control.get_selectionstr()
		print self.control.get_selectionparas()


