"""Subclass of Panel_controlprocess, which is generated by wxFormBuilder."""

import wx
import GUI_controlprocess
from LuaProgrammingGUI.test.control.control_process import control_process
from LuaProgrammingGUI.test.control.tools import view_tools

# Implementing Panel_controlprocess
class panel_process( GUI_controlprocess.Panel_controlprocess ):
	def __init__( self, parent, id, pos, size, style ):

		self.parent = parent
		self.control = control_process.Control(self)
		self.change_status = False
		self.current_func_str = ''
		self.current_choosen = None
		GUI_controlprocess.Panel_controlprocess.__init__(self, parent)
		view_tools.config_control(self, id, pos, size, style)
		self.m_treeControl_show.Bind(wx.EVT_TREE_SEL_CHANGED, self.refresh_current_selection)

	# Handlers for Panel_controlprocess events.
	# def check_save_status( self, event ):
	# 	self.control.monitor_changes(event, self.change_status)


	def add_functions( self, event ):
		# TODO: Implement add_functions
		self.change_status = True
		self.control.append_item()


	def delete_functions( self, event ):
		# TODO: Implement delete_functions
		self.change_status = True
		self.control.delete_item()


	def take_function_up( self, event ):
		# TODO: Implement take_function_up
		self.change_status = True
		self.control.change_item_position('up')

	def take_function_down( self, event ):
		# TODO: Implement take_function_down
		self.change_status = True
		self.control.change_item_position('down')

	def save_change( self, event ):
		# TODO: Implement save_change
		self.change_status = False

		ret, ret_msg = self.control.save_to_disk()
		wx.MessageBox(ret_msg)

	def redo_edit( self, event ):
		# TODO: Implement redo_edit
		self.change_status = True

		self.control.load_from_disk()

	def refresh_current_selection( self, event ):
		print 'refresh_current_selection ...'

		self.control.refresh_current_selection()

	def modify_runtime( self, event ):

		self.control.modify_runtime()